//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlowModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowFreeTable
    {
        public int id { get; set; }
        public string PlayerName { get; set; }
        public Nullable<int> NumActions { get; set; }
    }
}
