//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GravilotaModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EssenceScore
    {
        public int Id { get; set; }
        public string PlayerName { get; set; }
        public int BlueScore { get; set; }
        public int GreenScore { get; set; }
        public int OrangeScore { get; set; }
        public int PurpleScore { get; set; }
        public int RedScore { get; set; }
        public int YellowScore { get; set; }
    }
}
